spring:
  application:
    name: MTLSServer
---
server:
  port: 9002
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:server.jks
    key-store-password: serverpassword
    key-alias: server
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:server.jks
    trust-store-password: serverpassword
    trust-store-type: JKS