spring:
  application:
    name: MTLSClient
---
server:
  port: 9001
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:client.jks
    key-store-password: clientpassword
    key-alias: client
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:client.jks
    trust-store-password: clientpassword
    trust-store-type: JKS
---
endpoint:
  mtls-service: https://localhost:9002/api/name/{name}
  description: Sanvi Aarna